version: '3.0'
volumes:
  app-volume: {}
services:
  mysql:
    container_name: mysql
    image: daocloud.io/library/mysql:5.7 # 使用官方镜像
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=123456 # root用户密码
    volumes:
      - ./src/core/sql:/docker-entrypoint-initdb.d/
    ports:
      - 3307:3306
  website:
    container_name: nginx
    image: daocloud.io/library/nginx:latest # 使用官方镜像
    ports:
      - 3000:80
    # 挂载目录
    volumes:
      - ./vhosts.conf:/etc/nginx/conf.d/default.conf
      - app-volume:/usr/share/nginx/html

  server:
    # 用来指定一个包含Dockerfile文件的路径。一般是当前目录. 。Fig将build并生成一个随机命名的镜像
    build: .
    # 镜像
    image: nest-server:v0.1
    # 容器名称
    container_name: nest-server
    # 指定与部署和运行服务相关的配置（restart: always关机或者重启docker同时重启容器）
    restart: always
    ports:
      - 3001:3000
    # 添加环境变量
    environment:
      DB_HOST: "mysql"
    depends_on:
      - mysql
    volumes:
      - app-volume:/frontend-build/dist
